/**
 * Generated-app test emitter (`app/test/spec.test.mjs`).
 *
 * The emitted file runs with plain `node --test test/` on Node ≥ 20 and
 * imports only `node:` built-ins — it is the executable form of the app
 * directory's invariants, and it must keep passing after the platform is
 * deleted ("delete the platform" promise, ADR-0004).
 *
 * The template is spec-independent on purpose: it derives its expectations
 * from `spec.json` at test runtime, so it detects drift between a
 * hand-edited `spec.json` and the compiled migration instead of blessing
 * whatever the compiler emitted.
 */

import type { AppSpec } from "@openrupiv/spec";

export function renderSpecTest(spec: AppSpec): string {
  return `// Invariant tests for the "${spec.app.slug}" app directory.
// Generated by @openrupiv/compiler. Runs standalone with plain Node >= 20:
//
//   node --test test/
//
// Zero dependencies by design: node:test and node:assert only. The app
// directory is declarative data (ADR-0004); these tests check its internal
// consistency without any platform code.
import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const rawSpec = readFileSync(new URL("../spec.json", import.meta.url), "utf8");
const migration = readFileSync(
  new URL("../migrations/0001_init.sql", import.meta.url),
  "utf8",
);

let spec = null;
let specParseError = null;
try {
  spec = JSON.parse(rawSpec);
} catch (error) {
  specParseError = error;
}

function requireSpec() {
  assert.equal(
    specParseError,
    null,
    "spec.json must parse as JSON: " + specParseError,
  );
  assert.ok(
    spec !== null && typeof spec === "object" && !Array.isArray(spec),
    "spec.json must be a JSON object",
  );
  return spec;
}

// Must mirror the compiler's SQL naming convention exactly:
// PascalCase/camelCase -> snake_case.
function snakeCase(name) {
  return name
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase();
}

test("spec.json parses as a JSON object", () => {
  requireSpec();
});

test("specVersion is 0.1", () => {
  assert.equal(requireSpec().specVersion, "0.1");
});

test("every workflow state exists on its entity's state field", () => {
  const s = requireSpec();
  for (const workflow of s.workflows ?? []) {
    const entity = (s.entities ?? []).find(
      (candidate) => candidate.name === workflow.entity,
    );
    assert.ok(
      entity,
      "workflow " + workflow.name + " names missing entity " + workflow.entity,
    );
    const stateField = (entity.fields ?? []).find(
      (field) => field.name === workflow.stateField,
    );
    assert.ok(
      stateField,
      "workflow " + workflow.name + " names missing state field " + workflow.stateField,
    );
    assert.equal(
      stateField.type,
      "enum",
      "state field " + workflow.stateField + " must be an enum",
    );
    const states = new Set(stateField.values ?? []);
    assert.ok(
      states.has(workflow.initial),
      "initial state " + workflow.initial + " is not a declared state",
    );
    for (const transition of workflow.transitions ?? []) {
      assert.ok(
        states.has(transition.from),
        "transition " + transition.name + " from-state " + transition.from + " is not a declared state",
      );
      assert.ok(
        states.has(transition.to),
        "transition " + transition.name + " to-state " + transition.to + " is not a declared state",
      );
    }
  }
});

test("every approval transition requires at least 2 distinct approvers", () => {
  const s = requireSpec();
  for (const workflow of s.workflows ?? []) {
    for (const transition of workflow.transitions ?? []) {
      if (transition.approval === undefined) continue;
      assert.ok(
        Number.isInteger(transition.approval.count) && transition.approval.count >= 2,
        "approval on transition " + transition.name + " must require >= 2 distinct approvers, got " + transition.approval.count,
      );
    }
  }
});

test("the migration creates every table the spec requires", () => {
  const s = requireSpec();
  const tables = [];
  for (const entity of s.entities ?? []) {
    tables.push(snakeCase(entity.name));
    for (const relation of entity.relations ?? []) {
      tables.push(snakeCase(entity.name) + "_" + snakeCase(relation.name));
    }
  }
  assert.ok(tables.length > 0, "spec must declare at least one entity");
  for (const table of tables) {
    assert.ok(
      migration.includes("CREATE TABLE " + table + " ("),
      "migration must create table " + table,
    );
  }
});

test("the migration enables pgcrypto before using gen_random_uuid()", () => {
  assert.ok(
    migration.startsWith("CREATE EXTENSION IF NOT EXISTS pgcrypto;"),
    "migration must start with the pgcrypto extension",
  );
});
`;
}
