/**
 * SQL migration emitter — projects the spec's entities into
 * `app/migrations/0001_init.sql` per the SQL conventions in
 * specs/phase-1-contracts.md §1.
 *
 * Determinism: output is a pure function of the spec. Table emission order
 * is a stable topological sort of reference dependencies (ties broken by
 * spec order) so inline `REFERENCES` clauses always point at tables that
 * already exist; reference cycles fall back to deferred
 * `ALTER TABLE … ADD CONSTRAINT` statements. Join tables come last.
 */

import type { AppSpec, EntityDef, FieldDef, RelationDef } from "@openrupiv/spec";
import {
  columnName,
  joinTableName,
  sqlLiteral,
  sqlStringLiteral,
  tableName,
} from "./naming";
import type { CompilerError } from "./types";

const SCALAR_SQL_TYPES = {
  string: "text",
  text: "text",
  number: "double precision",
  boolean: "boolean",
  date: "date",
  datetime: "timestamptz",
} as const;

/** Columns every entity table carries; user fields must not collide. */
const RESERVED_COLUMNS: ReadonlySet<string> = new Set([
  "id",
  "created_at",
  "updated_at",
]);

export type MigrationResult =
  | { ok: true; sql: string }
  | { ok: false; errors: CompilerError[] };

export function renderMigration(spec: AppSpec): MigrationResult {
  const errors = collectSqlErrors(spec);
  if (errors.length > 0) return { ok: false, errors };

  const { order, deferredFields } = planTableOrder(spec.entities);

  const statements: string[] = [];
  for (const entity of order) {
    statements.push(renderEntityTable(entity, deferredFields));
  }
  for (const entity of order) {
    for (const field of entity.fields) {
      if (!deferredFields.has(field)) continue;
      const table = tableName(entity.name);
      const column = columnName(field);
      // field.entity is guaranteed by collectSqlErrors above.
      const target = tableName(field.entity ?? "");
      statements.push(
        `ALTER TABLE ${table}\n  ADD CONSTRAINT ${table}_${column}_fkey FOREIGN KEY (${column}) REFERENCES ${target}(id);`,
      );
    }
  }
  for (const entity of spec.entities) {
    for (const relation of entity.relations ?? []) {
      statements.push(renderJoinTable(entity, relation));
    }
  }

  const header = [
    "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
    "",
    `-- Migration 0001_init for app "${spec.app.slug}" v${spec.app.version} (spec v${spec.specVersion}).`,
    "-- Generated by @openrupiv/compiler as a deterministic projection of app/spec.json.",
    "-- Forward-only: never edit a migration after it has been applied; add a new one.",
    "",
    "",
  ].join("\n");

  return { ok: true, sql: `${header}${statements.join("\n\n")}\n` };
}

/**
 * Defensive semantic checks for anything that would produce broken or
 * ambiguous DDL. Inputs are contractually pre-validated by
 * `validateSpec`, but emitting garbage SQL on a bad input would be a
 * silently swallowed failure — so these are typed hard errors instead.
 */
function collectSqlErrors(spec: AppSpec): CompilerError[] {
  const errors: CompilerError[] = [];
  const entityNames = new Set(spec.entities.map((entity) => entity.name));
  const tableOrigins = new Map<string, string>();

  const claimTable = (table: string, path: string, what: string) => {
    const existing = tableOrigins.get(table);
    if (existing !== undefined) {
      errors.push({
        code: "ERR_DUPLICATE_NAME",
        path,
        message: `${what} maps to SQL table "${table}", which collides with the declaration at ${existing}`,
      });
    } else {
      tableOrigins.set(table, path);
    }
  };

  for (const [i, entity] of spec.entities.entries()) {
    claimTable(tableName(entity.name), `/entities/${i}/name`, `entity "${entity.name}"`);

    const columnOrigins = new Map<string, string>();
    for (const [j, field] of entity.fields.entries()) {
      const path = `/entities/${i}/fields/${j}`;
      const column = columnName(field);

      if (RESERVED_COLUMNS.has(column)) {
        errors.push({
          code: "ERR_DUPLICATE_NAME",
          path: `${path}/name`,
          message: `field "${field.name}" maps to SQL column "${column}", which is reserved (id, created_at, updated_at are system columns)`,
        });
      } else if (columnOrigins.has(column)) {
        errors.push({
          code: "ERR_DUPLICATE_NAME",
          path: `${path}/name`,
          message: `field "${field.name}" maps to SQL column "${column}", which collides with the field at ${columnOrigins.get(column)}`,
        });
      } else {
        columnOrigins.set(column, path);
      }

      if (field.type === "enum" && (field.values === undefined || field.values.length === 0)) {
        errors.push({
          code: "ERR_BAD_ENUM",
          path,
          message: `enum field "${field.name}" has no values; cannot emit a CHECK constraint`,
        });
      }
      if (field.type === "reference") {
        if (field.entity === undefined) {
          errors.push({
            code: "ERR_BAD_REFERENCE",
            path,
            message: `reference field "${field.name}" has no target entity; cannot emit a foreign key`,
          });
        } else if (!entityNames.has(field.entity)) {
          errors.push({
            code: "ERR_BAD_REFERENCE",
            path: `${path}/entity`,
            message: `reference field "${field.name}" targets unknown entity "${field.entity}"`,
          });
        }
      }
    }

    for (const [j, relation] of (entity.relations ?? []).entries()) {
      const path = `/entities/${i}/relations/${j}`;
      if (relation.to === entity.name) {
        errors.push({
          code: "ERR_UNSUPPORTED_SECTION",
          path,
          message: `self-referential manyToMany relation "${relation.name}" on entity "${entity.name}" is not supported by compiler v0 (join-table column names would collide)`,
        });
        continue;
      }
      if (!entityNames.has(relation.to)) {
        errors.push({
          code: "ERR_UNKNOWN_ENTITY",
          path: `${path}/to`,
          message: `relation "${relation.name}" targets unknown entity "${relation.to}"`,
        });
        continue;
      }
      claimTable(
        joinTableName(entity.name, relation.name),
        `${path}/name`,
        `relation "${entity.name}.${relation.name}"`,
      );
    }
  }

  return errors;
}

interface TableOrderPlan {
  /** Entities in emission order (stable topological sort). */
  order: EntityDef[];
  /** Reference fields whose FK must be added by ALTER TABLE (cycles). */
  deferredFields: ReadonlySet<FieldDef>;
}

function planTableOrder(entities: readonly EntityDef[]): TableOrderPlan {
  const remaining = [...entities];
  const emitted = new Set<string>();
  const order: EntityDef[] = [];
  const deferredFields = new Set<FieldDef>();

  const isReady = (entity: EntityDef): boolean =>
    entity.fields.every(
      (field) =>
        field.type !== "reference" ||
        field.entity === undefined ||
        field.entity === entity.name || // self-references work inline
        emitted.has(field.entity) ||
        deferredFields.has(field),
    );

  while (remaining.length > 0) {
    const readyIndex = remaining.findIndex(isReady);
    if (readyIndex === -1) {
      // Reference cycle: defer the first blocked entity's unmet foreign
      // keys to ALTER TABLE statements, then re-plan. Deterministic —
      // "first" is spec order.
      const blocked = remaining[0]!;
      for (const field of blocked.fields) {
        if (
          field.type === "reference" &&
          field.entity !== undefined &&
          field.entity !== blocked.name &&
          !emitted.has(field.entity)
        ) {
          deferredFields.add(field);
        }
      }
      continue;
    }
    const entity = remaining.splice(readyIndex, 1)[0]!;
    emitted.add(entity.name);
    order.push(entity);
  }

  return { order, deferredFields };
}

function renderEntityTable(
  entity: EntityDef,
  deferredFields: ReadonlySet<FieldDef>,
): string {
  const columns = [
    "id uuid PRIMARY KEY DEFAULT gen_random_uuid()",
    ...entity.fields.map((field) => renderColumn(field, deferredFields.has(field))),
    "created_at timestamptz NOT NULL DEFAULT now()",
    "updated_at timestamptz NOT NULL DEFAULT now()",
  ];
  return `CREATE TABLE ${tableName(entity.name)} (\n  ${columns.join(",\n  ")}\n);`;
}

function renderColumn(field: FieldDef, deferReference: boolean): string {
  const column = columnName(field);
  const parts: string[] = [column];

  if (field.type === "enum") parts.push("text");
  else if (field.type === "reference") parts.push("uuid");
  else parts.push(SCALAR_SQL_TYPES[field.type]);

  if (field.required) parts.push("NOT NULL");
  if (field.unique) parts.push("UNIQUE");
  if (field.default !== undefined) parts.push(`DEFAULT ${sqlLiteral(field.default)}`);
  if (field.type === "enum") {
    const values = (field.values ?? []).map(sqlStringLiteral).join(", ");
    parts.push(`CHECK (${column} IN (${values}))`);
  }
  if (field.type === "reference" && !deferReference) {
    parts.push(`REFERENCES ${tableName(field.entity ?? "")}(id)`);
  }

  return parts.join(" ");
}

function renderJoinTable(entity: EntityDef, relation: RelationDef): string {
  const left = tableName(entity.name);
  const right = tableName(relation.to);
  const table = joinTableName(entity.name, relation.name);
  return [
    `CREATE TABLE ${table} (`,
    `  ${left}_id uuid NOT NULL REFERENCES ${left}(id),`,
    `  ${right}_id uuid NOT NULL REFERENCES ${right}(id),`,
    `  PRIMARY KEY (${left}_id, ${right}_id)`,
    ");",
  ].join("\n");
}
