/**
 * Small static/near-static emitters: `app/package.json` and
 * `app/server.mjs`.
 */

import type { AppSpec } from "@openrupiv/spec";

/**
 * `app/package.json` — exactly the shape fixed by
 * specs/phase-1-contracts.md §1: zero dependencies, tests run with plain
 * Node ≥ 20.
 */
export function renderAppPackageJson(spec: AppSpec): string {
  return `${JSON.stringify(
    {
      name: spec.app.slug,
      private: true,
      type: "module",
      scripts: { test: "node --test" },
    },
    null,
    2,
  )}\n`;
}

/**
 * `app/server.mjs` — optional entry that serves the app directory with
 * `@openrupiv/runtime`. The import is guarded: the app directory ships
 * with zero dependencies, so running this without the runtime installed
 * must produce a clear, machine-readable error — not a raw module
 * resolution stack trace.
 */
export const SERVER_ENTRY = `// Optional server entry — generated by @openrupiv/compiler.
//
// This app directory is declarative data (ADR-0004). Serving it requires the
// @openrupiv/runtime library (Apache-2.0), or anything else that implements
// the documented app-directory contract. The directory itself has zero
// dependencies; install @openrupiv/runtime next to it to use this entry, or
// run the app through the workspace's Docker Compose stack.

const appDir = new URL(".", import.meta.url).pathname;

let runtime;
try {
  runtime = await import("@openrupiv/runtime");
} catch {
  console.error(
    JSON.stringify({
      error: "ERR_RUNTIME_NOT_INSTALLED",
      message:
        "@openrupiv/runtime could not be imported. server.mjs is an optional entry: " +
        "install @openrupiv/runtime (Node >= 20) and retry, or serve this directory " +
        "with the openrupiv Compose stack. The app directory itself is dependency-free " +
        "data; only serving it needs the runtime library.",
    }),
  );
  process.exit(1);
}

await runtime.serveAppDir(appDir);
`;
