/**
 * Deterministic workspace scaffold: every file `openrupiv new` writes, as a
 * pure function of its inputs (name, session secret, monorepo path). No
 * timestamps, no environment reads, no network — same inputs, same bytes.
 *
 * The Compose + Dex contents here are the Phase 1 quickstart contract
 * (specs/phase-1-contracts.md §4, ADR-0002): postgres:16 with volume and
 * healthcheck, Dex with the static `openrupiv-local` client and the
 * `dev@example.com` user, and the runtime built from the monorepo checkout.
 * All development-only credentials are conspicuously marked.
 */

export interface WorkspaceFileInputs {
  /** Workspace (directory) name, kebab-case. */
  name: string;
  /** Hex session secret generated by `new` (>= 32 chars; lives in .env only). */
  sessionSecret: string;
  /** Absolute path of the openRupiv monorepo checkout (compose build context). */
  repoRoot: string;
}

export interface WorkspaceFile {
  /** Workspace-relative POSIX path. */
  path: string;
  contents: string;
}

/** DEV-ONLY identity constants (ADR-0002). Public by design; dev-mode only. */
export const DEV_OIDC_CLIENT_ID = "openrupiv-local";
export const DEV_OIDC_CLIENT_SECRET = "openrupiv-dev-secret";
export const DEV_USER_EMAIL = "dev@example.com";
export const DEV_USER_PASSWORD = "dev-password";
/** bcrypt("dev-password"), cost 10 — verified round-trip when generated. */
export const DEV_USER_PASSWORD_BCRYPT =
  "$2a$10$aFeX8WayUGOzJJgjk4JlvOIrVtXzzskYv7eATqQZZG.JlCdPH4PW2";
export const POSTGRES_IMAGE = "postgres:16";
export const DEX_IMAGE = "dexidp/dex:v2.39.1";

function openrupivYaml(): string {
  return `# openRupiv workspace configuration (spec v0.1).
#
# \`openrupiv generate "<description>"\` writes the generated app into ./app
# (spec.json + SQL migration + docs + standalone tests) and commits it, so
# change management stays PR-shaped from the very first artifact.
specVersion: "0.1"
app: null
`;
}

function gitignore(): string {
  return `# Local secrets and machine-specific configuration — never commit.
# .env holds SESSION_SECRET and the OPENRUPIV_REPO path for docker compose.
.env

# Dependencies and logs.
node_modules/
*.log
`;
}

function envFile(inputs: WorkspaceFileInputs): string {
  return `# DEV-ONLY local configuration. This file is gitignored — never commit it.

# Signs the runtime's session cookies (>= 32 chars enforced by the runtime).
# Generated by \`openrupiv new\`; regenerate any time (invalidates sessions).
SESSION_SECRET=${inputs.sessionSecret}

# Absolute path to your openRupiv monorepo checkout. docker-compose.yaml
# builds the runtime image from this directory using
# packages/runtime/Dockerfile.
OPENRUPIV_REPO=${inputs.repoRoot}
`;
}

function dockerComposeYaml(inputs: WorkspaceFileInputs): string {
  return `# ${inputs.name} — local development stack, written by \`openrupiv new\`.
#
# =====================================================================
#  DEV ONLY — DO NOT DEPLOY. This stack bundles the Dex IdP with
#  STATIC, PUBLICLY-KNOWN credentials (ADR-0002):
#    OIDC client:  ${DEV_OIDC_CLIENT_ID} / ${DEV_OIDC_CLIENT_SECRET}
#    login:        ${DEV_USER_EMAIL} / ${DEV_USER_PASSWORD}
#  Never expose it beyond localhost; never reuse these values.
#  Production: delete the \`dex\` service and point OIDC_ISSUER /
#  OIDC_CLIENT_ID / OIDC_CLIENT_SECRET at your organization's IdP
#  (and unset OPENRUPIV_DEV_MODE — the runtime then refuses the
#  bundled dev secret by design).
# =====================================================================
#
# Interpolated values (SESSION_SECRET, OPENRUPIV_REPO) come from ./.env,
# which \`openrupiv new\` generates and .gitignore keeps out of the repo.

services:
  postgres:
    image: ${POSTGRES_IMAGE}
    environment:
      POSTGRES_USER: openrupiv
      POSTGRES_PASSWORD: openrupiv-dev-password # DEV ONLY — Compose-network local
      POSTGRES_DB: openrupiv
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openrupiv -d openrupiv"]
      interval: 2s
      timeout: 3s
      retries: 30

  dex:
    # DEV ONLY identity provider (ADR-0002). Configuration in ./dex/config.yaml.
    image: ${DEX_IMAGE}
    command: ["dex", "serve", "/etc/dex/config.yaml"]
    volumes:
      - ./dex/config.yaml:/etc/dex/config.yaml:ro
    ports:
      # Your browser must reach the issuer under the SAME name the runtime
      # uses (http://dex:5556). One-time setup:
      #   echo "127.0.0.1 dex" | sudo tee -a /etc/hosts
      - "5556:5556"
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:5556/healthz"]
      interval: 2s
      timeout: 3s
      retries: 30

  runtime:
    build:
      # The openRupiv monorepo checkout is the build context so the image
      # can include workspace packages. Path comes from ./.env.
      context: \${OPENRUPIV_REPO:?set OPENRUPIV_REPO in .env to your openRupiv monorepo checkout}
      dockerfile: packages/runtime/Dockerfile
    environment:
      DATABASE_URL: postgres://openrupiv:openrupiv-dev-password@postgres:5432/openrupiv # DEV ONLY
      OIDC_ISSUER: http://dex:5556
      OIDC_CLIENT_ID: ${DEV_OIDC_CLIENT_ID}
      # DEV ONLY — the runtime refuses this secret unless OPENRUPIV_DEV_MODE=true.
      OIDC_CLIENT_SECRET: ${DEV_OIDC_CLIENT_SECRET}
      SESSION_SECRET: \${SESSION_SECRET:?set SESSION_SECRET in .env (openrupiv new generates it)}
      OPENRUPIV_DEV_MODE: "true"
      APP_DIR: /app-dir
      BASE_URL: http://localhost:3000
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      # The generated app directory (spec + migrations), read-only.
      - ./app:/app-dir:ro
    depends_on:
      postgres:
        condition: service_healthy
      dex:
        condition: service_healthy

volumes:
  pgdata:
`;
}

function dexConfigYaml(): string {
  return `# Dex development IdP configuration, written by \`openrupiv new\` (ADR-0002).
#
# =====================================================================
#  DEV ONLY — STATIC, PUBLICLY-KNOWN CREDENTIALS.
#    user:         ${DEV_USER_EMAIL} / ${DEV_USER_PASSWORD}
#    OIDC client:  ${DEV_OIDC_CLIENT_ID} / ${DEV_OIDC_CLIENT_SECRET}
#  Anyone with this file can log in. Never expose beyond localhost;
#  never reuse these values. Production replaces this entire service
#  with your organization's OIDC issuer (see workspace README).
# =====================================================================

# Issuer as seen by BOTH the runtime container and your browser. Add
# "127.0.0.1 dex" to /etc/hosts so the host resolves the same name
# during the login redirect (see workspace README).
issuer: http://dex:5556

storage:
  # In-memory: all Dex state resets on restart. Correct for dev;
  # deliberately useless for anything else.
  type: memory

web:
  http: 0.0.0.0:5556

oauth2:
  # Dev convenience only: skip the consent screen.
  skipApprovalScreen: true

staticClients:
  - id: ${DEV_OIDC_CLIENT_ID}
    name: openRupiv local dev
    # DEV ONLY secret — the runtime refuses it unless OPENRUPIV_DEV_MODE=true.
    secret: ${DEV_OIDC_CLIENT_SECRET}
    redirectURIs:
      - http://localhost:3000/auth/callback

# DEV ONLY static password store. This is Dex's own demo mechanism, not an
# openrupiv password table — ADR-0003 holds: the runtime only speaks OIDC.
enablePasswordDB: true
staticPasswords:
  - email: ${DEV_USER_EMAIL}
    # bcrypt("${DEV_USER_PASSWORD}"), cost 10.
    hash: "${DEV_USER_PASSWORD_BCRYPT}"
    username: dev
    userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
`;
}

function readmeMd(inputs: WorkspaceFileInputs): string {
  return `# ${inputs.name}

An [openRupiv](https://github.com/openrupiv) workspace. Apps here are
generated as a reviewable declarative spec plus a deterministic projection
(ADR-0001) and served by the shared runtime engine (ADR-0004) — the LLM
never writes application code.

## Quickstart: described app running locally in under 10 minutes

Prerequisites: Docker with Compose v2, git, an openRupiv monorepo checkout
(v0 runs the CLI from it — its path is recorded as \`OPENRUPIV_REPO\` in
this workspace's \`.env\`), and an Anthropic API key.

**1. Generate the app.** From the monorepo checkout:

\`\`\`sh
export ANTHROPIC_API_KEY="<your key>"   # read from the environment only; never written to disk
corepack pnpm --filter @openrupiv/cli exec tsx src/main.ts \\
  generate "an approval workflow for vendor onboarding with 4-eyes review" \\
  --dir "<path to this workspace>"
\`\`\`

This writes \`./app\` (spec.json, SQL migration, docs, standalone tests)
and commits it to this repository with your git identity.

**2. One-time host setup.** The runtime and your browser must both reach
the Dex issuer under the same name (\`http://dex:5556\`):

\`\`\`sh
echo "127.0.0.1 dex" | sudo tee -a /etc/hosts
\`\`\`

**3. Start the stack** (first run pulls postgres/dex images and builds the
runtime image from your monorepo checkout):

\`\`\`sh
docker compose up --build
\`\`\`

**4. Log in.** Open <http://localhost:3000>, sign in as
\`${DEV_USER_EMAIL}\` / \`${DEV_USER_PASSWORD}\`, and use the app.

## What is running

| Service  | Image / build                              | Port | Purpose                          |
|----------|--------------------------------------------|------|----------------------------------|
| postgres | \`${POSTGRES_IMAGE}\` (volume: \`pgdata\`)   | —    | App persistence                  |
| dex      | \`${DEX_IMAGE}\`                             | 5556 | DEV-ONLY OIDC identity provider  |
| runtime  | built from \`$OPENRUPIV_REPO\` (packages/runtime/Dockerfile) | 3000 | Serves \`./app\` |

## DEV-ONLY credentials — read before deploying anything

Everything below is **public knowledge** and exists only so local
development works with zero identity configuration (ADR-0002):

| What                 | Value                                        |
|----------------------|----------------------------------------------|
| Login user           | \`${DEV_USER_EMAIL}\` / \`${DEV_USER_PASSWORD}\` |
| OIDC client          | \`${DEV_OIDC_CLIENT_ID}\` / \`${DEV_OIDC_CLIENT_SECRET}\` |
| Postgres             | \`openrupiv\` / \`openrupiv-dev-password\`    |

The runtime **refuses to start** with the bundled dev client secret unless
\`OPENRUPIV_DEV_MODE=true\` is set — the compliant path is the default path.

**Going to production** is one seam: delete the \`dex\` service, point
\`OIDC_ISSUER\` / \`OIDC_CLIENT_ID\` / \`OIDC_CLIENT_SECRET\` at your
organization's IdP, set a fresh \`SESSION_SECRET\`, and remove
\`OPENRUPIV_DEV_MODE\`. There is no password table to migrate — openRupiv
is OIDC-only from the first commit (ADR-0003).

## Workspace layout

\`\`\`
openrupiv.yaml        workspace config (spec v0.1)
docker-compose.yaml   local dev stack (postgres + dex + runtime)
dex/config.yaml       DEV-ONLY IdP configuration
.env                  SESSION_SECRET + OPENRUPIV_REPO (gitignored)
app/                  generated app — appears after \`openrupiv generate\`
\`\`\`

Regenerating: run \`openrupiv generate\` again. The \`./app\` directory is
rewritten from the new spec and committed, so every change is reviewable
git history.
`;
}

/**
 * All files `openrupiv new` writes, sorted by path. Pure function —
 * determinism is tested.
 */
export function workspaceFiles(inputs: WorkspaceFileInputs): WorkspaceFile[] {
  const files: WorkspaceFile[] = [
    { path: ".env", contents: envFile(inputs) },
    { path: ".gitignore", contents: gitignore() },
    { path: "README.md", contents: readmeMd(inputs) },
    { path: "dex/config.yaml", contents: dexConfigYaml() },
    { path: "docker-compose.yaml", contents: dockerComposeYaml(inputs) },
    { path: "openrupiv.yaml", contents: openrupivYaml() },
  ];
  return files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}
